// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEMwise.DataIngestion.Data;

#nullable disable

namespace STEMwise.DataIngestion.Migrations.Api
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEMwise.DataIngestion.Data.FxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FromCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ToCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FromCurrency", "ToCurrency")
                        .IsUnique();

                    b.ToTable("FxRates");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Data.SalaryProjection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ConfidenceHigh")
                        .HasColumnType("bigint");

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ConfidenceLow")
                        .HasColumnType("bigint");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataAgeMonths")
                        .HasColumnType("int");

                    b.Property<int>("DataYear")
                        .HasColumnType("int");

                    b.Property<string>("EntryLevelAdjNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EntryLevelSalary")
                        .HasColumnType("bigint");

                    b.Property<string>("MetroSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ProjectedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("ProjectedMedian")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectedPct25")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectedPct75")
                        .HasColumnType("bigint");

                    b.Property<long>("RawMedian")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "RoleSlug", "MetroSlug")
                        .IsUnique();

                    b.ToTable("SalaryProjections");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Data.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsJSkipDesignated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetroSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuitionCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TuitionIntlLocal")
                        .HasColumnType("bigint");

                    b.Property<long?>("TuitionIntlUsd")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("Universities");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Data.UniversityOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfidenceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataAgeMonths")
                        .HasColumnType("int");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("EmploymentRatePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<long?>("MedianSalaryLocal")
                        .HasColumnType("bigint");

                    b.Property<long?>("MedianSalaryUsd")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UniversityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("UniversityOutcomes");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Data.UniversityOutcome", b =>
                {
                    b.HasOne("STEMwise.DataIngestion.Data.University", "University")
                        .WithMany()
                        .HasForeignKey("UniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });
#pragma warning restore 612, 618
        }
    }
}
