// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STEMwise.DataIngestion.Data;

#nullable disable

namespace STEMwise.DataIngestion.Migrations.Ingestion
{
    [DbContext(typeof(IngestionDbContext))]
    [Migration("20260430180743_AddVisaMetrics")]
    partial class AddVisaMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STEMwise.DataIngestion.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LaunchOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OccupationSystem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryReportingFreq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "US",
                            Currency = "USD",
                            IsActive = true,
                            LaunchOrder = 1,
                            Name = "United States",
                            OccupationSystem = "SOC-2018",
                            SalaryPeriod = "annual",
                            SalaryReportingFreq = "bimonthly"
                        },
                        new
                        {
                            Code = "GB",
                            Currency = "GBP",
                            IsActive = true,
                            LaunchOrder = 2,
                            Name = "United Kingdom",
                            OccupationSystem = "SOC-2020",
                            SalaryPeriod = "annual",
                            SalaryReportingFreq = "annual"
                        },
                        new
                        {
                            Code = "CA",
                            Currency = "CAD",
                            IsActive = true,
                            LaunchOrder = 3,
                            Name = "Canada",
                            OccupationSystem = "NOC-2021",
                            SalaryPeriod = "annual",
                            SalaryReportingFreq = "monthly"
                        },
                        new
                        {
                            Code = "AU",
                            Currency = "AUD",
                            IsActive = true,
                            LaunchOrder = 4,
                            Name = "Australia",
                            OccupationSystem = "ANZSCO-2013",
                            SalaryPeriod = "annual",
                            SalaryReportingFreq = "annual"
                        },
                        new
                        {
                            Code = "JP",
                            Currency = "JPY",
                            IsActive = true,
                            LaunchOrder = 5,
                            Name = "Japan",
                            OccupationSystem = "JSOC-2011",
                            SalaryPeriod = "monthly",
                            SalaryReportingFreq = "annual"
                        });
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawFxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceApi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrency", "TargetCurrency")
                        .IsUnique();

                    b.ToTable("RawFxRates");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawH1bRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PrevailingWage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Quarter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WageLevel")
                        .HasColumnType("int");

                    b.Property<string>("WorksiteCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorksiteState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawH1bRecords");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawSalaryBenchmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataCollectionYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("EmploymentRatePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("Median")
                        .HasColumnType("bigint");

                    b.Property<string>("MetroSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OccupationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Pct10")
                        .HasColumnType("bigint");

                    b.Property<long?>("Pct25")
                        .HasColumnType("bigint");

                    b.Property<long?>("Pct75")
                        .HasColumnType("bigint");

                    b.Property<long?>("Pct90")
                        .HasColumnType("bigint");

                    b.Property<string>("RoleSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "RoleSlug", "MetroSlug")
                        .IsUnique();

                    b.ToTable("RawSalaryBenchmarks");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawUniversity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsJSkipDesignated")
                        .HasColumnType("bit");

                    b.Property<string>("MetroSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TuitionCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("TuitionIntl")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CountryCode", "ExternalId")
                        .IsUnique();

                    b.ToTable("RawUniversities");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawUniversityOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DataYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("EmploymentRatePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("LoanDefaultRatePct")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("MedianSalaryLocal")
                        .HasColumnType("bigint");

                    b.Property<int>("RawUniversityId")
                        .HasColumnType("int");

                    b.Property<string>("RoleSlug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("VisaSuccessRatePct")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RawUniversityId");

                    b.ToTable("RawUniversityOutcomes");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawVisaMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisaCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawVisaMetrics");
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.SalaryGrowthRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualGrowthRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GrowthPeriodFrom")
                        .HasColumnType("int");

                    b.Property<int>("GrowthPeriodTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleSlug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SalaryGrowthRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnnualGrowthRate = 0.048m,
                            CountryCode = "US",
                            GrowthPeriodFrom = 2019,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7286),
                            RoleSlug = "software-engineer",
                            Source = "BLS-OES-historical"
                        },
                        new
                        {
                            Id = 2,
                            AnnualGrowthRate = 0.062m,
                            CountryCode = "US",
                            GrowthPeriodFrom = 2019,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7762),
                            RoleSlug = "data-scientist",
                            Source = "BLS-OES-historical"
                        },
                        new
                        {
                            Id = 3,
                            AnnualGrowthRate = 0.051m,
                            CountryCode = "US",
                            GrowthPeriodFrom = 2019,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7766),
                            RoleSlug = "cybersecurity-eng",
                            Source = "BLS-OES-historical"
                        },
                        new
                        {
                            Id = 4,
                            AnnualGrowthRate = 0.032m,
                            CountryCode = "US",
                            GrowthPeriodFrom = 2019,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7769),
                            RoleSlug = "electrical-engineer",
                            Source = "BLS-OES-historical"
                        },
                        new
                        {
                            Id = 5,
                            AnnualGrowthRate = 0.074m,
                            CountryCode = "US",
                            GrowthPeriodFrom = 2019,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7772),
                            RoleSlug = "ml-engineer",
                            Source = "BLS-OES-historical"
                        },
                        new
                        {
                            Id = 6,
                            AnnualGrowthRate = 0.042m,
                            CountryCode = "GB",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7775),
                            RoleSlug = "software-engineer",
                            Source = "ONS-ASHE-historical"
                        },
                        new
                        {
                            Id = 7,
                            AnnualGrowthRate = 0.058m,
                            CountryCode = "GB",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7778),
                            RoleSlug = "data-scientist",
                            Source = "ONS-ASHE-historical"
                        },
                        new
                        {
                            Id = 8,
                            AnnualGrowthRate = 0.049m,
                            CountryCode = "GB",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7781),
                            RoleSlug = "cybersecurity-eng",
                            Source = "ONS-ASHE-historical"
                        },
                        new
                        {
                            Id = 9,
                            AnnualGrowthRate = 0.031m,
                            CountryCode = "GB",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7784),
                            RoleSlug = "electrical-engineer",
                            Source = "ONS-ASHE-historical"
                        },
                        new
                        {
                            Id = 10,
                            AnnualGrowthRate = 0.048m,
                            CountryCode = "CA",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7787),
                            Source = "StatCan-LFS-historical"
                        },
                        new
                        {
                            Id = 11,
                            AnnualGrowthRate = 0.045m,
                            CountryCode = "AU",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7790),
                            RoleSlug = "software-engineer",
                            Source = "ABS-EEH-historical"
                        },
                        new
                        {
                            Id = 12,
                            AnnualGrowthRate = 0.060m,
                            CountryCode = "AU",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2025,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7792),
                            RoleSlug = "data-scientist",
                            Source = "ABS-EEH-historical"
                        },
                        new
                        {
                            Id = 13,
                            AnnualGrowthRate = 0.037m,
                            CountryCode = "JP",
                            GrowthPeriodFrom = 2020,
                            GrowthPeriodTo = 2024,
                            LastUpdated = new DateTime(2026, 4, 30, 18, 7, 41, 421, DateTimeKind.Utc).AddTicks(7795),
                            Source = "MHLW-historical"
                        });
                });

            modelBuilder.Entity("STEMwise.DataIngestion.Models.RawUniversityOutcome", b =>
                {
                    b.HasOne("STEMwise.DataIngestion.Models.RawUniversity", "University")
                        .WithMany()
                        .HasForeignKey("RawUniversityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("University");
                });
#pragma warning restore 612, 618
        }
    }
}
